# version: '2'
# services:
#   # rabbitmq:
#   #   image: rabbitmq:3-management
#   #   container_name: rabbitmq
#   #   ports:
#   #     - 15672:15672
#   #     - 5672:5672
#   #     - 5671:5671
#   # MongoDB: https://hub.docker.com/_/mongo/
#   # linux_ctr:
#   #   container_name: linux_ctr
#   #   build: .
#   #   links:
#   #     - "graylog:graylog"
#   #   depends_on:
#   #     - graylog

#   mongodb:
#     container_name: mongodb
#     image: mongo:3

#   # # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
#   # elasticsearch:
#   #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
#   #   environment:
#   #     - http.host=0.0.0.0
#   #     - transport.host=localhost
#   #     - network.host=0.0.0.0
#   #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#   #   ulimits:
#   #     memlock:
#   #       soft: -1
#   #       hard: -1
#   #   mem_limit: 1g

#   # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
#     container_name: Elasticsearch
#     environment:
#       - http.host=0.0.0.0
#       - transport.host=localhost
#       - network.host=0.0.0.0
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ports:
#         - 9200:9200
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     mem_limit: 1g

#   # elasticsearch:
#   #   volumes:
#   #     - es_data:/usr/share/elasticsearch/data
#   #   networks:
#   #     - amundsennet
#   #   ulimits:
#       # nofile:
#       #   soft: 65536
#       #   hard: 65536
          
#   # Graylog: https://hub.docker.com/r/graylog/graylog/
#   graylog:
#     container_name: graylog
#     image: graylog/graylog:3.3
#     environment:
#       # CHANGE ME (must be at least 16 characters)!
#       - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
#       # Password: admin
#       - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
#       - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
#       - GRAYLOG_ROOT_TIMEZONE=Asia/Singapore
#     links:
#       - mongodb:mongo
#       - elasticsearch
#     depends_on:
#       - mongodb
#       - elasticsearch
#     ports:
#       # Graylog web interface and REST API
#       - 9000:9000
#       # Syslog TCP
#       - 1514:1514
#       # Syslog UDP
#       - 1514:1514/udp
#       # GELF TCP port for TTP, Worker_1 and Worker_2
#       - "12201-12220:12201-12220"
#       # GELF UDP
#       - 12201:12201/udp
#     volumes: 
#       - ./:/usr/share/graylog/data/config/

version: '3'

services:

  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:4.2
    # networks:
    #   - graylog
  
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1g
    # networks:
    #   - graylog
  
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.0
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_PUBLISH_URI=http://127.0.0.1:9000/
      # Fix for Graylog-ES detection issue: https://github.com/Graylog2/graylog2-server/issues/9550
      - GRAYLOG_ELASTICSEARCH_VERSION=7 
    # networks:
    #   - graylog
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      # System Load Meta Tracking
      - 9100:9100
      - 9100:9100/udp
      # Synergos Director Meta Tracking
      - 9200:9200
      - 9200:9200/udp
      # Synergos TTP(s) Meta Tracking (Modify where necessary)
      - 9300:9300
      - 9300:9300/udp
      # Synergos Worker(s) Meta Tracking (Modify where necessary)
      - 9400:9400
      - 9400:9400/udp

    volumes: 
      - ./custom/config/:/usr/share/graylog/data/config/
      - ./custom/contentpacks/:/usr/share/graylog/data/contentpacks/

# networks:
#   graylog:
#     driver: bridge